### ISSUE TITLE
How to use this plugin with client version 5.0

### ISSUE THREAD

**Issue by Raagun** [rtcTo/rtc2gitcli#21]
Hello,
I was exploring this tool and got this error while trying to migrate:

`Unexpected exception
com.ibm.team.rtc.cli.infrastructure.internal.core.CLIClientException: com.ibm.team.filesystem.cli.core.util.CLIFileSystemClientException: Status ERROR: com.ibm.team.filesystem.cli.core code=2 Could not log in to https://url/: Your client is version 5.0.1, and the server is version 5.0.  These versions are not compatible.
Your client is version 5.0.1, and the server is version 5.0.  These versions are not compatible.
Check the log for details about the error at "C:\Users\user\AppData\Local\jazz-scm". If you have configured custom logging check your log configuration settings for the path to the log file. null`

Is there plugin versions for client 5.0?

**Comment by WtfJoke** [comment]
Hi Raagun,

This tool is an extension of the scm commandline provided by ibm. We included the link to version 5.0.1 in our readme (allthough version 6.0.1 is already out :) )

Long story short, you can find the scmTools for version 5.0 [HERE](https://jazz.net/downloads/rational-team-concert/releases/5.0?p=allDownloads) :+1:  

Please give us feedback, if it worked out for you. :smiley:

**Comment by Raagun** [comment]
Yes, but plugin does not compile with 5.0 and our server uses version 5.0.
Versions 5.0 and 5.0.1 are incompatible, produces the error.

**Comment by reinhapa** [comment]
Could you try it with the a prebuilt docker image `rtcto/rtc2git:5.0` and check if you still got the same problem?

**Comment by reinhapa** [comment]
Removed explicit versions for required RTC plugins. That way the build worked for me and Version 5.0
