### ISSUE TITLE
dtoEvolution Error

### ISSUE THREAD

**Issue by timeapen** [rtcTo/rtc2gitcli#24]
When I execute the scm load command to load the target workspace, I get the following error:

java.lang.IllegalStateException: Found two dtoEvolution elements with the same c
omponentVersion value in bundle com.ibm.team.scm.common.
at com.ibm.team.repository.common.internal.util.ModelElementDescriptor$E
volutionDescriptorComponentVersionComparator.compare(ModelElementDescriptor.java
:223)
at com.ibm.team.repository.common.internal.util.ModelElementDescriptor$E
volutionDescriptorComponentVersionComparator.compare(ModelElementDescriptor.java
:1)
at java.util.TreeMap.compare(TreeMap.java:1188)

Any ideas?

**Comment by fbuehlmann** [comment]
Are you working with our docker images or where you get this error?
Do you have the error too without the migration cli plugin?
Is the workspace name you are using unique or coudl there be an other workspace with the same name?
Have seen this kind of error when using Java8 with the RTC CLI.
