### ISSUE TITLE
Error during the scm migrate-to-git command

### ISSUE THREAD

**Issue by evandrojr** [rtcTo/rtc2gitcli#25]
Hi guys,

I get this error:
Subcomando "migrate-to-git" desconhecido

Which means:
subcommand "migrate-to-git" unknow

Do you have any idea of what I am doing wrong? Thanks!

**Comment by fbuehlmann** [comment]
Looks that the plugin is not recognized by the cli client.
Could you try to do the migration with the docker image we publisched?
