### ISSUE TITLE
Not getting hamcrest jar file in the lib by default

### ISSUE THREAD

**Issue by Srinath-MS** [rtcTo/rtc2gitcli#26]
I tried cloning the project and also downloading the project. Neither of them gave me the hamcrest jar file. I want to set break points and debug the code to learn how it works. Right now, I am facing failure with NoClassDefFoundError for the org.hamcrest class. I manually added the library and still getting the error. Could you please let me know what should be done to get the project loaded to eclipse properly and debug hassle free? 

Have attached a couple of screenshots for your reference:

![error](https://cloud.githubusercontent.com/assets/8194135/19316528/bf3767d2-906f-11e6-97ce-64fa3c3c2fb5.png)
![error_1](https://cloud.githubusercontent.com/assets/8194135/19316532/c2464f74-906f-11e6-906e-21b7c89b0d72.png)

**Comment by fbuehlmann** [comment]
This is an osgi plugin. Therefore you should debug and run it as an eclipse plugin. There is a run configuration for run/ debug of the project.

**Comment by ghost** [comment]
@Srinath-MS :Have u explored this solution ,able to load project propelry?
