### ISSUE TITLE
Binaries for rtc2git(cli)

### ISSUE THREAD

**Issue by Raynor83** [rtcTo/rtc2gitcli#27]
Hello there,

we are going to use this tool for migrating some **RTC 6.0.2** projects, but we can't build the rt2gitcli project due to problems with Eclipse/RTC Client build process. Is there a possibility of getting the binaries for (all) rtc2git repos?

Regards,

Raynor83

**Comment by fbuehlmann** [comment]
Would it be an option to use the docker image directly?

**Comment by reinhapa** [comment]
you could use a ready build docker image:
`docker run -v /var/rtc2git:/var/data -it --name rtc2git rtcto/rtc2git:6.0.2`
