### ISSUE TITLE
How do I install the plugin into the SCM tools?

### ISSUE THREAD

**Issue by timothymcmackin** [rtcTo/rtc2gitcli#28]
The Eclipse Requirements section of the readme implies some steps to import this tool into my Jazz  SCM tools, but doesn't spell them out. Can someone be a little more specific about how to install rtc2gitcli into my Eclipse/jazz scm setup? Thanks!

**Comment by WtfJoke** [comment]
I had some issues on the first time setup as well. I think thats also the reason why one my colleague came up with the [docker images](https://github.com/rtcTo/rtc2git-docker).

Neverthless I tried to install it after a quite long time. Here some advice, maybe it helps you.

1.  Configure SCMTools Target Platform described [here in the wiki](https://github.com/rtcTo/rtc2gitcli/wiki/configure-target-platform). Point to the folder where your scm.exe/lscm.bat is (If you use eclipse classic aka non javaee eclipse, install the Eclipse Plugin Development Tools as described - (I was using scm tools from rtc 5.01))
2. Clone this repo and import it in eclipse as maven project
3. Open pom.xml and follow the hint to install the missing maven connector
4. Update maven project using ALT+F5
5. By this point the project shouldnt contain any errors (make sure you have still your created target platform in window preference selected)
6.  You should have an launch-configuration named rtc2git --> start it
7. In your console window you should see "Help for: scm migrate-to-git"
8.  Open the launch-config and edit the command in arguments/program arguments

**Comment by reinhapa** [comment]
@timothymcmackin is your question answered so far?

**Comment by timothymcmackin** [comment]
@reinhapa Yes, that answers my question. Thanks!

**Comment by himmakam** [comment]
Here it mentioned about maven project. But someone be very specific about below plugin - I tried many options, but getting some class not found issues. I searched almost all the issues here, but not seeing the fix for the same. Appreicate anyone's help here. 

 "Also you need to get the latest version of the rtc2gitcli plugin JAR file. This has to be placed into the plugins/ directory."

**Comment by jlczuk** [comment]
I cannot find this rtc2gitcli jar and I have been unable to create it in Eclipse following the instructions in the wiki.  I am totally blocked.

**Comment by ghost** [comment]
@reinhapa reinhapa :getting issues for setting up project in eclipse with respect to plugin can u please help
