### ISSUE TITLE
How to prepare the SRC and DST workspaces?

### ISSUE THREAD

**Issue by verhasi** [rtcTo/rtc2gitcli#30]
It is not clear for me how to prepare the SRC and DST workspaces for the migration. As I run the tool it finds no changeset at all even the stream has a lot.

"TOTAL NUMBER OF CHANGESETS [0]"

In the SRC workspace I set the components to the first baseline and the flow to the stream, in the DST workspace I set the flow to SRC. I tried also with or without the components in the DST but the same result.

Regards,
Istvan

**Comment by fbuehlmann** [comment]
For SRC workspace add all components with initial baselines and set the stream target to DST workspace. On the DST workspace add all components from stream that should be migrated. 
The tool then try to bring the SRC workspace to the same level as the DST workspace by accepting each changeset step by step.
At at later time you can accept all changes from stream to DST workspace and start an incremental migration

**Comment by verhasi** [comment]
Hi Florian,

Thank you for the response. Still not success. Actually if I set the Flow target in src to dst 
![image](https://user-images.githubusercontent.com/2287064/27035806-f768d898-4f82-11e7-9903-c1cd6cd53135.png)
i got NPE at line MigrateTo.java:226
```
IWorkspaceHandle sourceStreamHandle = (IWorkspaceHandle) (sourceWsConnection.getFlowTable()
					.getCurrentAcceptFlow().getFlowNode());
```
If in the dst workspace set the flow target to src then got he zero number of changesets.

**Comment by fbuehlmann** [comment]
Set stream target from SRC to DST and set the Stream Target to current and default.

**Comment by verhasi** [comment]
I applied the following
![image](https://user-images.githubusercontent.com/2287064/27079678-e0a5752e-5038-11e7-9c18-d99f172ce871.png)
but still zero number of changeset :(

**Comment by fbuehlmann** [comment]
Create a SRC workspace that follow the stream you like to migrate. Check that the SRC workspace has the latest changes accepted from the stream. 
Now create the DST workspace that contains all components from the stream but with the initial baseline. Now set the flow target from the DST to the SRC and set it as default and current.

Attached two screenshots from my environment:
![image](https://user-images.githubusercontent.com/16190783/27080119-d466b410-503a-11e7-8896-c1b1d913b337.png)

![image](https://user-images.githubusercontent.com/16190783/27080105-c3516012-503a-11e7-9389-8cf4ab8dbe84.png)

**Comment by verhasi** [comment]
Thank you for the detailed instructions. In this way it started to work. On your screenshot in the DST workspace I see the latest changes but I applied the baseline. I just mention if someone else is coming do follow the instructions of text and not the screenshot.

**Comment by rambaliga** [comment]
Had I seen these comments before, I would have saved 2 weeks of trial and error that I did to understand this utility. Can the instructions not be updated? Would save lot of time.
