### ISSUE TITLE
SCM tools version 6.x

### ISSUE THREAD

**Issue by ycon-company** [rtcTo/rtc2gitcli#41]
I currently use scmtools v5.0.2 for the migration process 
Sometimes during migration I encounter issues and errors deriving from scmtools cli,
and I read online that many of these issues are resolved in v6.
However, when trying to run migration with scmtools v6.x it seems not compatible with rtc2gitcli.

Do you have any suggestions / experience with using scmtools v6.x for migration process?

Thanks!
Yael

**Comment by reinhapa** [comment]
@ycon123 unfortunately we got no experiences using v6.x versions, due the fact that we have migrated now almost 2 years ago. What I know out of the past that your client should match the actual RTC server version. So if you want to use the v6.x version of the client you will need to upgrade your server to at least also an v6.x version first...

**Comment by ycon-company** [comment]
Our RTC server is already V6 
I thought maybe someone who tried migration with scmtools v6 could have some suggestions..

**Comment by WtfJoke** [comment]
Sadly, we dont know anybody in person, who have tried migration with scmtools v6.
Did you try using the docker image of [rtcTo/rtc2git-docker](https://github.com/rtcTo/rtc2git-docker)?

Unless you havent tried, you can also try [rtcTo/rtc2git](https://github.com/rtcTo/rtc2git). It's maybe a bit less likely to fail and easier to adjust, in case of errors.

**Comment by ycon-company** [comment]
I can try using the docker image. However - isn't just an image using scmtool v5 as advised in the rtc2git documentation? I believe the errors I experience will reproduce in this environment also.. but I'm willing to try!

About the rtc2git project - I remember I read in one of the issues that this tool may be slower and maybe rtc2gitcli is better for migrating large scale projects and changesets (which is what we are facing).

**Comment by reinhapa** [comment]
I've updated the [rtc2git-docker project](https://github.com/rtcTo/rtc2git-docker/) for v6.x lately with some additions of @akoptelov made in the past. In the project  [README](https://github.com/rtcTo/rtc2git-docker/blob/java_plugin/README.adoc) you should find a documentation how to get a docker image that contains the correct RTC version including the _rct2gitcli_ extension.

He could may be help you also with some hints when you got problems with [rtc2gitcli](https://github.com/rtcTo/rtc2gitcli) within the docker image.

**Comment by akoptelov** [comment]
@ycon123 Sorry for missing the thread. Actually I did migration using scmtools v60 to match our server version and found no issues with it.
Can you describe what kind of incompatibility you encountered? And how did you build the extension?

**Comment by reinhapa** [comment]
@akoptelov @WtfJoke you're welcome to join our Slack Channel under [https://rtc.to/#slack](https://rtc.to/#slack)

**Comment by ycon-company** [comment]
Hi @akoptelov !

Details about my environment:
RTC server - v6.0.2 
Eclipse Mars 64bit + RTC plugin v6.0.2
I import the rtc2gitcli project as Maven project to Eclipse.
Then I configure target platform to be location of scm.exe on my local disk.

When I choose scmtool_v5 I am able to run migrate-to-git commands (specifically **help migrate-to-git** runs successfully)
But when I choose scmtools_v6 as target platform - I get the attached message.
![image](https://user-images.githubusercontent.com/14972986/29288809-d7d1d222-8142-11e7-8982-1d1f0e2718b8.png)

I'm currently logged into #slack if someone if available to chat about this issue..:)

**Comment by WtfJoke** [comment]
> When I choose scmtool_v5 I am able to run migrate-to-git commands (specifically help migrate-to-git runs successfully)
> But when I choose scmtools_v6 as target platform - I get the attached message.

I was able to reproduce the same error using scm tools 6.0.2. In the meantime im in slack too.

**Comment by reinhapa** [comment]
@WtfJoke is this issue still unresolved?

**Comment by WtfJoke** [comment]
It can be closed. Ycon was able to solve it with my support. Allthough I wasnt able to solve it on my pc

**Comment by WtfJoke** [comment]
@ycon123  You know how you solved the error?
