### ISSUE TITLE
Help needed on using this tool

### ISSUE THREAD

**Issue by kaiilin** [rtcTo/rtc2gitcli#43]
Hi, 
I have set up the migration tool and RTC source/target workspace. I tried to migrate a simple RTC repository as a test but it failed with the following error.  What does it mean?

        _Could not initialize data area. Directory is not shared: E:\share_

I am not quite sure how this work to migrate the code to github. Is there somewhere I need to provide the github connection information? does this tool work with private enterprise github server?

**Comment by akoptelov** [comment]
@kaiilin It looks like scm can't find its metadata in E:\share_. Did you load your workspace there?
```scm load -r <uri> -u <username> -P <password> <TARGET_WORKSPACE>```

**Comment by kaiilin** [comment]
@akoptelov 
Thanks. I revised to point to the right directory and it seems complete the migration process. What should I do to move it github? thanks.

**Comment by akoptelov** [comment]
@kaiilin Now you have a local git repo. You can create a new repo at GitHub and add it as a remote repository to your local one:
```git remote add github <github repo url>```
And then finally push changes to github:
```git push github master```

**Comment by kaiilin** [comment]
@akoptelov 
thanks for your help. understood.

**Comment by sarathkrishna2018** [comment]
I get this exception when I run it:
org.eclipse.jgit.api.errors.JGitInternalException: Exception caught during execution of add command. It is weird. But when I hardcode the sandbox directory value to lets say "C:/sandbox". It gives me "Directory is not shared" exception. Then I try load TARGET_WORKSPACE into C:/sandbox. The migration complete, but I dont know/find where the git repository is. Can you please help me?

**Comment by kaiilin** [comment]
Hi, the migration initiate the target folder as local git repo. You may follow what @akoptelov suggested to me to push your content to github. Thanks
