### ISSUE TITLE
Migration command was successful but cant see any changesets.

### ISSUE THREAD

**Issue by AnupKSeth** [rtcTo/rtc2gitcli#58]
Hi,

I have used the migration command as below.

scm migrate-to-git -r <uri> -u <username> -P <password> -m <migration.properties> <SOURCE_WORKSPACE> <TARGET_WORKSPACE>

The command is executing successfully now with no error, however, it is not showing any baselines or changesets. We have multiple changesets and baselines.

Things I have done.

Before using this command, I have created a source workspace and target workspace.

![source_ws](https://user-images.githubusercontent.com/56344678/66473016-12ab4700-eaac-11e9-9122-29bd8e2ae993.jpeg)

![target_ws](https://user-images.githubusercontent.com/56344678/66473037-1b9c1880-eaac-11e9-8cf6-3c452644e697.jpeg)

after this I have loaded initial target workspace with below command.

scm load -r <uri> -u <username> -P <password> <TARGET_WORKSPACE>

Attaching the screen shot of actual migration.

I had run migration command twice.

1.   In first attempt, below line is commented in "migration.properties"
#rtc.baseline.include=^(.*)$

![migration1](https://user-images.githubusercontent.com/56344678/66473472-f2c85300-eaac-11e9-8eaa-0d4c80ab9266.jpeg)

2. I re run the command with the below line not commented in second attempt.
rtc.baseline.include=^(.*)$

![migration2](https://user-images.githubusercontent.com/56344678/66473533-11c6e500-eaad-11e9-8fb4-67c8571e8697.jpeg)

Attaching final folder structure screen shot.

![image](https://user-images.githubusercontent.com/56344678/66473602-33c06780-eaad-11e9-837c-5434f96a1900.png)

In this folder I can not see any code or projects or components. So the command is not showing any error but don't know if migration was successful.

am I missing any steps ?

**Comment by WtfJoke** [comment]
Hi @AnupKSeth 

I dont see any issues at your point to be honest. Workspace setup looks correct. 
If you load target workspace and open it in eclipse, are there any incoming changesets?

**Comment by dibehara** [comment]
I too face the exact same issue as reported by @AnupKSeth. I am not able to find the changesets being captured anywhere and the migration log says that the migration is completed. There is nowhere in the log that I could find the logs wrt to the changesets. Migration is in just 63 seconds.

**Comment by AnupKSeth** [comment]
> Hi @AnupKSeth
> 
> I dont see any issues at your point to be honest. Workspace setup looks correct.
> If you load target workspace and open it in eclipse, are there any incoming changesets?

Hi,

I have opened the target workspace in eclipse and below is the screen shots of the workspace.  Target workspace is "TW1" and source workspace is "SW1".


![image](https://user-images.githubusercontent.com/56344678/67362917-d7b81180-f589-11e9-996e-efeeee6bcf5e.png)


![image](https://user-images.githubusercontent.com/56344678/67362933-e56d9700-f589-11e9-9371-c6c8eccb4255.png)


what do I have to do next ? do we need to load all the code into the "TW1" and then push that to GIT ? please help what needs to be done further as we do not see any code in "TW1".

**Comment by dibehara** [comment]
Also, Can you provide some more clarity on these steps:

1) step into the target directory.
- I don't see the target directory in your GitHub repository code. Is it something that will be generated by executing the "mvn clean install" command? If yes, Then I had executed the mvn command but it throws some error called package doesn't exists. This is because, some of the packages are being used from the Plugin dependencies jars. 
Request you to please help.

**Comment by WtfJoke** [comment]
> 1. step into the target directory.

It means step into any directory, where you want to have the migration takes place.

> This is because, some of the packages are being used from the Plugin dependencies jars.
Request you to please help.

If you followed the readme, you should have a green workspace and should be able to build the project. If in doubt you can also try to follow this [wiki-entry](https://github.com/rtcTo/rtc2gitcli/wiki/Setup)

**Comment by WtfJoke** [comment]
> what do I have to do next ? do we need to load all the code into the "TW1" and then push that to GIT ? please help what needs to be done further as we do not see any code in "TW1".

What happens if you accept one of these components (for example build_commons)?
If it loads only the initial state of that component (and afterwards there are incoming changesets), then you should probably do that on each component and retry.

TBH im not really familiar with rtc2gitcli issues (I have built rtc2git only). 

Keen to know, how it works out.

**Comment by AnupKSeth** [comment]
> > what do I have to do next ? do we need to load all the code into the "TW1" and then push that to GIT ? please help what needs to be done further as we do not see any code in "TW1".
> 
> What happens if you accept one of these components (for example build_commons)?
> If it loads only the initial state of that component (and afterwards there are incoming changesets), then you should probably do that on each component and retry.
> 
> TBH im not really familiar with rtc2gitcli issues (I have built rtc2git only).
> 
> Keen to know, how it works out.

After migration command is successful, i get below folder structure.

![image](https://user-images.githubusercontent.com/56344678/67844869-80cfb080-fb24-11e9-8fdc-24969fde8e72.png)


Now since I want to migrate my code from RTC to GIT, I do not see any projects that exists in my components in this target workspace. So i guess I need to load all the projects from all the components in my TW1 and then add those projects to staging area and then push it to my remote repository . 

Is my understanding correct ?

**Comment by WtfJoke** [comment]
The folder structure is just an empty git repo. 

The procedure includes loading the initial workspace (in your case TW1). Either at that point there should be already projects listed or at least during the first changeset. 

I would guess that you need to load all the projects and make that initial commit and afterwards proceed with the migration command

**Comment by smartarix** [comment]
I'm still struggling a bit to run this, Where should I pass git url ?
I looked into migration.properties file but didn't saw any property for git repo uri.
any help is appreciated.

**Comment by WtfJoke** [comment]
Hi @smartarix 
You dont need to pass a git url. It creates a local git repo. 
You can then distribute this like any other local git repo by adding a git remote and push it to a git server like github.

**Comment by WtfJoke** [comment]
Will close this issue, since I havent got any answer. @smartarix please open a new issue if you experience any problems with migration.
