### ISSUE TITLE
Error on importing rtc2gitcli project into eclipse.

### ISSUE THREAD

**Issue by AnupKSeth** [rtcTo/rtc2gitcli#59]
Hi,

On importing the "rtc2gitcli" project in eclipse getting below error. How do we resolve it ?

![image](https://user-images.githubusercontent.com/56344678/66640636-f12a9680-ec36-11e9-9605-f3dba98f57ce.png)

**Comment by WtfJoke** [comment]
Hi @AnupKSeth 

Usually eclipse should find it automatically. 
You can install the maven dependency plugin manually by using this eclipse marketplace link:
https://marketplace.eclipse.org/content/m2e-connector-maven-dependency-plugin

**Comment by AnupKSeth** [comment]
> Hi @AnupKSeth
> 
> Usually eclipse should find it automatically.
> You can install the maven dependency plugin manually by using this eclipse marketplace link:
> https://marketplace.eclipse.org/content/m2e-connector-maven-dependency-plugin

Hi ,

this link has worked fine and the error is gone.

Thanks, closing the issue
