### ISSUE TITLE
How to include the changesets of the source workspace?

### ISSUE THREAD

**Issue by dibehara** [rtcTo/rtc2gitcli#60]
I see in the logs that the migration is complete for all the Tags but It is not showing the changeset information. The complete migration is not able to find the changesets in the entire process and also the migration shows it took just 0 seconds for each tag that it migrates. Can somebody please advise me on why it is not including/showing me the changeset information in the migration process? Thank you. 
I executed the below step:

scm migrate-to-git -r <uri> -u <username> -P <password> -m <migration.properties> <SOURCE_WORKSPACE> <TARGET_WORKSPACE>

**Comment by WtfJoke** [comment]
Answer was provided in #58 

Feel free to reopen if the answer isnt sufficient for you
