### ISSUE TITLE
Problem with scm load -r <uri> -u <username> -P <password> <TARGET_WORKSPACE>

### ISSUE THREAD

**Issue by manjeetdangi123** [rtcTo/rtc2gitcli#61]
Problem with scm load -r <uri> -u <username> -P <password> <TARGET_WORKSPACE>
uri I have used as clone url -> https://github.com/rtcTo/rtc2gitcli.git
username password i usually used to login to Git.
Target workspace as C:\DevSoftware\Migration\TARGET_WORKSPACE. 

But still it shows following error.

C:\DevSoftware\Migration\RTC-scmTools-Win64-6.0.4\jazz\scmtools\eclipse>scm load -r https://github.ibm.com/manjeetdangi/CCBT.git -u manjeetdangi -P ######## C:\DevSoftware\Migration\TARGET_WORKSPACE
Problem running 'load':
Could not log in to https://github.ibm.com/manjeetdangi/CCBT.git as user manjeetdangi: CRJAZ2917E The repository on the following server cannot be reached: https://github.ibm.com/manjeetdangi/CCBT.git. Verify that the server address is correct.Try logout and re-login with the updated credentials if the password has been changed.
CRJAZ2917E The repository on the following server cannot be reached: https://github.ibm.com/manjeetdangi/CCBT.git. Verify that the server address is correct.
Check the log for details about the error at "C:\Users\ManjeetDangi\AppData\Local\jazz-scm". If you have configured custom logging check your log configuration settings for the path to the log file.

**Comment by WtfJoke** [comment]
Hi Manjeet,

> scm load -r https://github.ibm.com/manjeetdangi/CCBT.git
Here you should link to your RTC-Repository eg. RTC-Server instead (and not on your git repo). 

Hope that helps 👍

**Comment by manjeetdangi123** [comment]
Still not able to get this command , still getting the same error

C:\DevSoftware\Migration\RTC-scmTools-Win64-6.0.4\jazz\scmtools\eclipse>scm load -r https://igartc02.swg.usma.ibm.com/jazz/resource/itemOid/com.ibm.team.scm.Workspace/_ALc38Iw6Eemg0pzbEncc-w -u manjeetdangi -P ****** C:\DevSoftware\Migration\TARGET_WORKSPACE
Problem running 'load':
Could not log in to https://igartc02.swg.usma.ibm.com/jazz/resource/itemOid/com.ibm.team.scm.Workspace/_ALc38Iw6Eemg0pzbEncc-w as user manjeetdangi: CRJAZ2917E The repository on the following server cannot be reached: https://igartc02.swg.usma.ibm.com/jazz/resource/itemOid/com.ibm.team.scm.Workspace/_ALc38Iw6Eemg0pzbEncc-w. Verify that the server address is correct.Try logout and re-login with the updated credentials if the password has been changed.
CRJAZ2917E The repository on the following server cannot be reached: https://igartc02.swg.usma.ibm.com/jazz/resource/itemOid/com.ibm.team.scm.Workspace/_ALc38Iw6Eemg0pzbEncc-w. Verify that the server address is correct.
Check the log for details about the error at "C:\Users\ManjeetDangi\AppData\Local\jazz-scm". If you have configured custom logging check your log configuration settings for the path to the log file.

**Comment by WtfJoke** [comment]
Try using just https://igartc02.swg.usma.ibm.com
Eg. `scm load -r https://igartc02.swg.usma.ibm.com ...`

**Comment by manjeetdangi123** [comment]
Still not able to resolve this issue

C:\DevSoftware\Migration\RTC-scmTools-Win64-6.0.4\jazz\scmtools\eclipse>scm load -r https://igartc02.swg.usma.ibm.com -u manjeetdangi -P @@@@@@ C:\DevSoftware\Migration\TARGET_WORKSPACE
Problem running 'load':
Could not log in to https://igartc02.swg.usma.ibm.com as user manjeetdangi: CRJAZ2382E Cannot connect to the repository at URL "https://igartc02.swg.usma.ibm.com". This can happen if you have supplied an incorrect URI or if the server is down. Try logout and re-login with the updated credentials if the password has been changed.
CRJAZ2382E Cannot connect to the repository at URL "https://igartc02.swg.usma.ibm.com". This can happen if you have supplied an incorrect URI or if the server is down.
Check the log for details about the error at "C:\Users\ManjeetDangi\AppData\Local\jazz-scm". If you have configured custom logging check your log configuration settings for the path to the log file.

**Comment by WtfJoke** [comment]
Usually the url ends with ccm. 

https://igartc02.swg.usma.ibm.com/jazz/
Or
https://igartc02.swg.usma.ibm.com/ccm

I usually took the url of my eclipse (connection details)
But in general this is not an rtc2git issue. You can search through the scm documentation of ibm.

**Comment by manjeetdangi123** [comment]
Yes it worked with https://igartc02.swg.usma.ibm.com/jazz

**Comment by manjeetdangi123** [comment]
Now I am facing this issue with the above command, 


C:\DevSoftware\Migration\RTC-scmTools-Win64-6.0.4\jazz\scmtools\eclipse>scm load -r manjeet Hello C:\DevSoftware\Migration\TARGET_WORKSPACE


Where i have used 
manjeet as nickname for userid and password for my repository.
Hello is my workspace i need to load.
Error::
Problem running 'load':
Component "C:\DevSoftware\Migration\TARGET_WORKSPACE" is not found or the user does not have access to it.


Also I am able to run the following command successfully.

C:\DevSoftware\Migration\RTC-scmTools-Win64-6.0.4\jazz\scmtools\eclipse>scm load -r manjeet Hello
Successfully loaded items into the sandbox.


I want to know what is this sandbox. What is the location of this sandbox in my local computer.

and how I am going to move forward with the 2nd command of the code .
scm migrate-to-git -r <uri> -u <username> -P <password> -m <migration.properties> <SOURCE_WORKSPACE> <TARGET_WORKSPACE>

after successfully running the 1st command. 
1.Do i need to download/clone this code to my RSA/Eclipse . 
2. Make this code error free.
3. Build this code. 
4. Then run this command
