### ISSUE TITLE
JGitInternalException - Exception caught during execution of add command

### ISSUE THREAD

**Issue by smartarix** [rtcTo/rtc2gitcli#64]
I'm running migrate-to-git but getting error - 
JGitInternalException - Exception caught during execution of add command

PFA for detailed error log

![IMG_2039](https://user-images.githubusercontent.com/17400912/79099475-d837a500-7d81-11ea-9332-701d97489c68.jpg)

**Comment by WtfJoke** [comment]
Can you describe what the cause of the issue was, in case another user finds themself in the same error?

**Comment by daytalker** [comment]
have the same issue but do not find a solution.
@smartarix Can you please share the solution you found?
