### ISSUE TITLE
Query on zip file migration

### ISSUE THREAD

**Issue by smartarix** [rtcTo/rtc2gitcli#65]
I perfromed migration succesfully for couple of project however for some of my project from RTC to Bitbucket, we observed some descripencies.

1 .zip file migrated from RTC to BB but no RTC history migrated to Bitbucket
2, .xlsx file migrated but has more history in BB than RTC

Is above are limitations of this tool ?

**Comment by WtfJoke** [comment]
Hi @smartarix 
Is this related to your in the meantime created issue #66 ? 

The tool should migrate all files (except if you exclude some file extensions).  So it should migrate all files with all the history present in rtc (except cvs/svn history migrated already to rtc).

**Comment by smartarix** [comment]
Yes, I'm closing this issue.
