### ISSUE TITLE
Wrong implementation of format properties 

### ISSUE THREAD

**Issue by fabieu** [rtcTo/rtc2gitcli#70]
https://github.com/rtcTo/rtc2gitcli/blob/c02aa0e6bbbd554a63e18f6b58d18612e7933e49/migration.properties#L58
With the argument %1s (or %2s) you refer to a general conversion with a minimum width of 1 (or 2) - There is no reason to set a width there, right?
Reference: https://docs.oracle.com/javase/7/docs/api/java/util/Formatter.html

This is working just fine if you dont want to change the order of the git commit message components:  rtc workitem number ->  rtc commit message -> rtc workitem summary as mentioned here #32 

In my opion the argument index $ should be used instead so that the the actual index of the method parameters at String.format() are getting addressed rather than their bare order. So **%1$s %2$s %3$s** will give the same result as before but now it is possible to customize the commit message even more by doing something like that: **%3$s %2$s**, which will print the rtc workitem summary in front of the rtc commit message and completly skip the rtc workitem number.

In addition to that i would also add a documentation for the %3$s parameter added in #34 

I am going to create a merge request if a get positive feedback to my recommandation.

**Comment by ghost** [comment]
anyone implemented this solution?would like to understand how the structure should be in git,each stream should be one git repo ?

**Comment by fabieu** [comment]
> anyone implemented this solution?would like to understand how the structure should be in git,each stream should be one git repo ?

Hey @satish1729-hash, this issue is only related to the format of the commit message. You can decide on your own if you want to migrate all components or only specific ones from one stream into a single git repo. Refer to [this](https://github.com/rtcTo/rtc2gitcli/wiki/Home-of-rtc2gitcli) wiki page for an instruction how to accomplish this task.
