### ISSUE TITLE
maven plugin connector error

### ISSUE THREAD

**Issue by ghost** [rtcTo/rtc2gitcli#71]
while loading the project to eclipse and running got error for plugin.please find error screenshot below.
please help how to fix 
![image](https://user-images.githubusercontent.com/68590891/98642369-5552e900-2368-11eb-8210-e2bdecb43559.png)

**Comment by WtfJoke** [comment]
Hi @satish1729-hash 
I understand that you have problems using the software, but please dont write in so many old (and closed) issues and mention everyone. Please keep in mind this is an open source project, which is not actively maintained anymore (since we dont have any rtc available to test as we migrated couple years ago). So all response are in our spare free time :)

My notifications:
![grafik](https://user-images.githubusercontent.com/7139697/99046969-cc1ffa00-2593-11eb-9178-e8a58b7c1a5a.png)

If you have some spare time have a look how other open source projects use this code of conduct.
https://www.contributor-covenant.org/version/2/0/code_of_conduct/


For your problem: Which eclipse do you use?  On which os are you? When you continue to suffer problems, you could try to use the [rtc2git docker image](https://github.com/rtcTo/rtc2git-docker).

**Comment by satish1729-hash** [comment]
Appreciated your response.i am using eclipse version 2020-09 (4.17.0)

**Comment by WtfJoke** [comment]
I cannot reproduce this problem with latest eclipse (2020-09 4.17.0).
![grafik](https://user-images.githubusercontent.com/7139697/99063318-9fc0a980-25a4-11eb-8c26-e7e8ce4bf9c6.png)

Did you activated the target platform and followed the [step by step](https://github.com/rtcTo/rtc2gitcli/#setup-eclipse-development-environment)?

My target platform for reference (in case you use eclipse classic you need to install eclipse plugin development tools, also [described here in the wiki](https://github.com/rtcTo/rtc2gitcli/wiki/configure-target-platform)):
![grafik](https://user-images.githubusercontent.com/7139697/99063531-ee6e4380-25a4-11eb-82e3-791e5bd12392.png)

**Comment by satish1729-hash** [comment]
Thanks alot for your response.
Yes followed all the steps,may be I will try to setup again,not sure
whether not able to get the respective plugin..

One more help, can you please clarify about source_workspace and
targer_workspace set up.if you can provide details with some example and
screenshot if helps alot.

**Comment by satish1729-hash** [comment]
Plugin execution not covered by lifecycle configuration: org.apache.maven.plugins:maven-dependency-plugin:2.1:copy-dependencies (execution: copy-dependencies, phase: process-sources)

Error while downloading 'http://maven.apache.org/xsd/maven-4.0.0.xsd'


i am getting this error, could you please clarify whether any connector directly download and place in plugin path?

**Comment by WtfJoke** [comment]
> Error while downloading 'http://maven.apache.org/xsd/maven-4.0.0.xsd'

Are you behind a proxy? I have no problems downloading this xsd. 

> One more help, can you please clarify about source_workspace and
targer_workspace set up.if you can provide details with some example and
screenshot if helps alot.

As others already pointed out, [in this wiki entry](https://github.com/rtcTo/rtc2gitcli/wiki/Home-of-rtc2gitcli#setup-the-workspaces) you see how source_workspace and target_workspace is set up with an example.

**Comment by satish1729-hash** [comment]
Thanks alot spending time for me..

Yes I saw the workspace setup wiki page.

Few queries,

1. In source_workspace setup ,I will mention the components which I want to
migrate,what should be the flow_target for source_workspace ,we can leave
the default one which is appearing ?
2. In target_workspace it is mentioned that
all the components from stream but with initial base line?how set that base
line for component ,could you please clarify?

3.How source_workspace and target_workspace works ?I mean generally
workspace means it will get the entire stream data based on component
selection.when we give flow target of targer_workspace as source _workspace
will it capture the history change commits from source_workspace ?

**Comment by satish1729-hash** [comment]
One more clarification, could you please provide screenshot in which folder
this xsd file should present ?I will try to download the file and place
whether it works

**Comment by WtfJoke** [comment]
>One more clarification, could you please provide screenshot in which folder
this xsd file should present ?I will try to download the file and place
whether it works

The xsd allone wont help. I honestly dont know how to install them manually. 
I ziped my just downloaded eclipse and uploaded it (will delete it in a few days), this might work (as it contains the installed m2 connector). 

https://drive.google.com/file/d/1mUIPvDKiRH_VisoA4EzmEWklMXr1A-xz/view

If it doesnt work just try to setup your eclipse in a proxy-free network/place.

**Comment by satish1729-hash** [comment]
Thanks alot for your help..I will download and check this first.

Could you please clarify on my queries related to workspaces also which are
mentioned din earlier comments.
How to set initial baseline for components in target_workspace I am not
clear .Please share me screenshots if possible.

**Comment by WtfJoke** [comment]
> 1. In source_workspace setup ,I will mention the components which I want to migrate,what should be the flow_target for source_workspace ,we can leave the default one which is appearing ?

Flow target should be the stream you want to migrate. If you create the story from a stream thats the default one which is appearing yes. 



> 2. In target_workspace it is mentioned that all the components from stream but with initial base line?how set that base line for component ,could you please clarify?

There is a wiki entry in rtc2git, see here https://github.com/rtcTo/rtc2git/wiki/Resetting-your-workspace-to-an-older-state


> 3.How source_workspace and target_workspace works ?I mean generally workspace means it will get the entire stream data based on component selection.when we give flow target of targer_workspace as source _workspace will it capture the history change commits from source_workspace ?

Generally how rtc works (as far as I remember):
Usually RTC Workspaces capture the state of the flow target (usually a stream). When changes are getting published to the flow target(eg stream), you see them in your workspace as incoming changes.

To your question:
Target_workspace (resetted to an old state/code -> initial baseline) has the source_workspace as flow_target. Source workspace has the to be migrating stream as flowtarget. So far you have 1 workspace (target_workspace) with the most oldest codebase and 1 workspace (source_workspace) with the most recent codebase.

This means target_workspace have all changesets (as incoming changes) which source_workspace already have accepted. 
So when you accept changeset after changeset in target_workspace you can redo the history. And on each step, we do the same change with git. Thats the idea.

**Comment by ramjag1729** [comment]
Need your help for one more item,In commit history complete commit message not present in git history .

I tried to modify parameter(commit.message.format) in migration.properties file but could not able to get exact commit message .Could you please provide details how to keep commit message.format value to get complete RTC history commit message to git commit comment .

Example: 
RTC history commit message:
123:Test message- change on 20200101

Git history commit message :
123 change on 20200101

So message is trimmed and displayed in git comment .in above example Test message is missing ,content between : and - symbol
